#!/bin/bash

# Cleanup 
for pVersion in 3 5 6 7; do
  if [ -d "/Library/Python/2.${pVersion}/site-packages/PIL/" ]; then
    if [ ! -f "/usr/local/bin/pip" ]; then
      sudo easy_install-2.7 pip
    fi
    sudo pip uninstall Pillow
  fi
done


  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew prune

brew install libjpeg freetype
 
# Check for freetype's destination
if [ ! -d "/usr/local/include/freetype" ]; then
  ln -s $(brew info freetype | grep "usr" | awk '{print $1}')/include/freetype2 /usr/local/include/freetype
  ln -s $(brew info freetype | grep "usr" | awk '{print $1}')/include/ft2build.h /usr/local/include/
  ln -s $(brew info freetype | grep "usr" | awk '{print $1}')/lib/libfreetype.6.dylib /usr/local/lib/
  ln -s $(brew info freetype | grep "usr" | awk '{print $1}')/lib/libfreetype.6.dylib /usr/local/lib/libfreetype.dylib
fi

# install Pillow
cd /Applications
curl -O -L https://github.com/pypa/pip/raw/master/contrib/get-pip.py
sudo python get-pip.py
rm /Applications/get-pip.py
sudo cp /System/Library/Frameworks/Python.framework/Versions/2.7/bin/pip /usr/bin
sudo mkdir /Library/Frameworks/Python.framework/Versions/2.7
sudo cp -r /System/Library/Frameworks/Python.framework/Versions/2.7/* /Library/Frameworks/Python.framework/Versions/2.7

sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future pip install Pillow
