#!/bin/bash

# Cleanup 
if [ -d "/Library/Python/2.7/site-packages/PIL/" ]; then
  sudo pip uninstall Pillow
fi

# Ceck for brew and install it
if [ ! -f "/usr/local/bin/brew" ]; then
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
fi

# Install libs
if [ ! -d $(brew info libjpg | grep "usr" | awk '{print $1}') ]; then
  brew install libjpeg 
fi
if [ ! -d $(brew info freetype | grep "usr" | awk '{print $1}') ]; then
  brew install freetype
fi

# Check for freetype's destination
if [ ! -d "/usr/local/include/freetype" ]; then
  ln -s $(brew info freetype | grep "usr" | awk '{print $1}')/include/freetype2 /usr/local/include/freetype
  ln -s $(brew info freetype | grep "usr" | awk '{print $1}')/include/ft2build.h /usr/local/include/
  ln -s $(brew info freetype | grep "usr" | awk '{print $1}')/lib/libfreetype.6.dylib /usr/local/lib/
  ln -s $(brew info freetype | grep "usr" | awk '{print $1}')/lib/libfreetype.6.dylib /usr/local/lib/libfreetype.dylib
fi

brew install libjpeg freetype

# install Pillow
sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future pip install Pillow

